name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  Tests:

    runs-on: windows-latest
        
    env:
      Project_Directory: NiL.Exev
      Solution_Name: $Project_Directory/NiL.Exev.csproj
      Test_Project_Path: Tests/Tests.csproj
      Nuget_Pack_Output_Directory: nuget

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Install .NET Core 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Decode the snk
      run: |
        $snk_byte = [System.Convert]::FromBase64String("${{ secrets.SNK_KEY }}")
        $certificatePath = Join-Path -Path $env:Project_Directory -ChildPath keys.snk
        [IO.File]::WriteAllBytes("$certificatePath", $snk_byte)

    - name: Restore dependencies
      run: |
        cd ./NiL.Exev
        dotnet clean
        dotnet restore
        cd ..

    - name: Build
      run: |
        cd ./NiL.Exev
        dotnet build --no-restore -c Release -property:SignAssembly=false -property:PublicSign=false
        cd ..

    - name: Run TinyT4
      run: |
        cd Tests
        dotnet run --project ..\Utils\tiny-t4\ --framework net7.0

    - name: Test .NET Core 7.0
      run: |
        cd Tests
        dotnet test -c Release -property:TargetFramework=net7.0 -property:SignAssembly=false -property:PublicSign=false

    - name: Remove the snk
      run: Remove-Item -path NiL.Exev\keys.snk
